### ISSUE TITLE
Заполнение формы "Пожаловаться на рекламу"

### ISSUE THREAD

**Issue by lenapanova** [lenapanova/Test-mail.ru#1]
- Как воспроизвести:
  1) Открыть sport.mail.ru
  2) Перейти к кнопке "Обратная связь"
  3) "Пожаловаться на рекламу"
  4) Вписать ящик проблемного ящика
- Фактический результат:
  Нельзя ввести самостоятельно адрес проблемного ящика, есть возможность только указать из списка.
- Ожидаемый результат:
  Имеется возможность самостоятельно ввести адрес проблемного ящика.

**Comment by arendario** [comment]
"Вписать ящик проблемного ящика" - куда вписать? У меня во всех полях получилось указать разные адреса (вручную).
https://help.mail.ru/sport_support/marketing_WARNING_DOUBLES_1

**Comment by MaryPrimak** [comment]
Проверила обратную связь, при заполнении формы у меня получилось ввести свой адрес, посмотрите скриншот.
[Почтовый ящик.docx](https://github.com/lenapanova/Test-mail.ru/files/575808/default.docx)

**Comment by arendario** [comment]
Лена, прокомментируйте, пожалуйста. Может, мы неправильно что-то делаем.
Я пока оценку ставить не буду.

**Comment by lenapanova** [comment]
Все правильно делаете. Сейчас все в порядке, здесь бага уже нет
