### ISSUE TITLE
Графа поиска

### ISSUE THREAD

**Issue by lenapanova** [lenapanova/Test-mail.ru#2]
Как воспроизвести:
1) Открыть sport.mail.ru
2) Перейти к графе поиска
3) Ввести "Гольф"

Фактический результат:
Не выдается информация, относящаяся к гольфу.

Ожидаемый результат:
Выдается информация, которая относится к гольфу.

**Comment by arendario** [comment]
Жаль, скриншота нет :(
Сегодня выдается информация https://sport.mail.ru/search/?q=%D0%B3%D0%BE%D0%BB%D1%8C%D1%84

**Comment by MaryPrimak** [comment]
У меня также выдало правильный результат. Скриншот прилагаю.
[Гольф.docx](https://github.com/lenapanova/Test-mail.ru/files/575822/default.docx)
